# Generated by Django 3.2.6 on 2023-12-11 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('num_words', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCorrections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_errors', models.JSONField()),
                ('corrections', models.JSONField()),
                ('doc_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfupload.documentdetails')),
            ],
        ),
    ]
